#!/bin/bash

if [ $# -lt 2 ] ; then
	echo "Usage: start [1,2,3,4] [0,1] [n]
1 - httpd
2 - tomcat
3 - listener
4 - all

0 - stop
1 - start

n - number of tomcat servers"
	exit 0
else if [ $1 -eq 1 ] ; then
	if [ $2 -eq 0 ] ; then
		echo "Stoping httpd..."
		sudo ./httpd/bin/httpd -k stop
	else if [ $2 -eq 1 ] ; then
		echo "Starting httpd..."
		sudo ./httpd/bin/httpd -k start
	fi fi
else if [ $1 -eq 2 ] ; then
	for i in `seq 1 $3` ; do
		if [ $2 -eq 0 ] ; then
			echo "Stoping tomcat$i..."
			sh tomcat$i/bin/catalina.sh stop
		else if [ $2 -eq 1 ] ; then
			echo "Starting tomcat$i..."
			sh tomcat$i/bin/catalina.sh start
		fi fi
	done
else if [ $1 -eq 3 ] ; then
	echo "Starting listener..."
	sudo ./cpumonitor/listener
else if [ $1 -eq 4 ] ; then
	if [ $2 -eq 0 ] ; then
		for i in `seq 1 $3` ; do
			echo "Stoping tomcat$i..."
			sh tomcat$i/bin/catalina.sh stop
		done
		echo "Stoping httpd..."
		sudo ./httpd/bin/httpd -k stop
	else if [ $2 -eq 1 ] ; then
		for i in `seq 1 $3` ; do
			echo "Starting tomcat$i..."
			sh tomcat$i/bin/catalina.sh start
		done
		echo "Starting httpd..."
		sudo ./httpd/bin/httpd -k start
		echo "Starting listener..."
		sudo ./cpumonitor/listener
	fi fi 
fi fi fi fi fi
